baseURL = "https://thoha.xyz"
languageCode = "en-au"
title = "Thoha Arsyad"
copyright = "🗼"

paginate = 3

theme = "minima"

[author]
name = "Thoha Arsyad"
slogon = "Also known as thohars."
description = "According to all known laws of aviation, there is no way a bee should be able to fly. Its wings are too small to get its fat little body off the ground. The bee, of course, flies anyway because bees don't care what humans think is impossible."

[params]
iam = "I am"
subtitle = ""
timeformat = "02 Jan, 2006"
switch = ["✨", "🍅"]
defaultTheme = "dark"
# If set true, date of posts will be shown in the homepage.
displayDate = true
# If set true, users can select text from your post.
selectable = true
# Custom global font. notice: `globalFontFamily` won't be working
# on texts in some special positions like on titles
globalFontFamily = ""
# If set true, all your posts will use the chosen comment plugin
# except those with a `comment: false` in their front-matter
commentOnAllPosts = false
# toc decides the shape of the toc button. e.g. default, lines, bar
toc = "lines"

recent = "Recent Posts"
older = "Older Posts"

[[params.social]]
name = "twitter"
url = "https://twitter.com/thohars"
svg = ""
[[params.social]]
name = "email"
url = "mailto:mail@thoha.xyz"
svg = ""
[[params.social]]
name = "rss"
url = "/rss"
svg = ""

[[params.info]]
name = "Public key"
url = "/thoha.asc"

[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Posts"
url = "/post"
weight = 2

# You can classify your posts by setting taxanomies in the front matter
# e.g.
#     categories = ["dev"]
#     series = ["Building an RPC server"]
#     tags = ["hugo", "golang"]
# A little suggestion: one post belongs to one series or one category or multiple tags.
[taxonomies]
tag = "tags"

# Fields below make sure all the codes in a post are
# highlighted correctly, so better not edit them.
[markup.highlight]
lineNos = true
noClasses = false
